name: SimpleTrades
version: 2.1
main: com.kiro.trading.SimpleTrading
author: Kiro
description: Trading plugin based on Matzefratze's

commands:
  tra:
    usage: /<command>
    description: Basic Trading